#!/usr/bin/env node
'use strict';

const program = require('commander');
const app = require('./src/app');

program
  .version('1.0.0')
  .description('Wild Code School - Quizs');

program
  .command('startApp', {isDefault: true})
  .alias('start')
  .description('Start QCM')
  .action(() => {
    app.start();
  });

program.parse(process.argv);